/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsageRouteImport } from './routes/_app.usage'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppPlaygroundRouteImport } from './routes/_app.playground'
import { Route as AppModelsRouteImport } from './routes/_app.models'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppDocsRouteImport } from './routes/_app.docs'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/docs': typeof AppDocsRoute
  '/logs': typeof AppLogsRoute
  '/models': typeof AppModelsRoute
  '/playground': typeof AppPlaygroundRoute
  '/support': typeof AppSupportRoute
  '/usage': typeof AppUsageRoute
}
export interface FileRoutesByTo {
  '/api-keys': typeof AppApiKeysRoute
  '/billing': typeof AppBillingRoute
  '/docs': typeof AppDocsRoute
  '/logs': typeof AppLogsRoute
  '/models': typeof AppModelsRoute
  '/playground': typeof AppPlaygroundRoute
  '/support': typeof AppSupportRoute
  '/usage': typeof AppUsageRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/playground': typeof AppPlaygroundRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/docs'
    | '/logs'
    | '/models'
    | '/playground'
    | '/support'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api-keys'
    | '/billing'
    | '/docs'
    | '/logs'
    | '/models'
    | '/playground'
    | '/support'
    | '/usage'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/api-keys'
    | '/_app/billing'
    | '/_app/docs'
    | '/_app/logs'
    | '/_app/models'
    | '/_app/playground'
    | '/_app/support'
    | '/_app/usage'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDocsRoute: typeof AppDocsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppSupportRoute: typeof AppSupportRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppDocsRoute: AppDocsRoute,
  AppLogsRoute: AppLogsRoute,
  AppModelsRoute: AppModelsRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppSupportRoute: AppSupportRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
